---
- hosts: localhost
  gather_facts: no
  remote_user: ubuntu
  become: yes
  connection: local 
  tasks:
    - name: Install docker and some dependencies
      apt:
        name: python3-pip, docker.io
        state: present
        sudo: yes
    - name: Start docker service
      service:
        name: docker
        state: started
        sudo: yes
    - name: Install docker python module
      pip:
        name: docker
