---
- hosts: localhost
  gather_facts: no
  remote_user: ubuntu
  become: yes
  connection: local 
  tasks:
    - name: St
      docker_container:
        name: back  
        image: echrysanthakopou/back:1_0_0
        state: started
        recreate: yes
        published_ports:
          - 8082:8082
