spring:
  datasource:
    url: jdbc:mysql://${DB_IP}:${DB_PORT}/${DB_SCHEMA}?useSSL=false&createDatabaseIfNotExist=true&useUnicode=true&connectionCollation=utf8_general_ci&allowPublicKeyRetrieval=true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect