apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
  namespace: pensionapp
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: backend